# Generated by Django 3.0.5 on 2020-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_quiztopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztopic',
            name='topic_code',
            field=models.CharField(max_length=10),
        ),
    ]
